# Note: This is an experimental, untested and incomplete action!
name: Pyaket Setup

runs:
  using: composite
  steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Credentials
      run: |
        git config user.name github-actions[bot]
        git config user.email 41898282+github-actions[bot]@users.noreply.github.com
      shell: bash

    - name: Setup uv
      uses: astral-sh/setup-uv@v6

    - name: Setup Rust
      uses: dtolnay/rust-toolchain@stable

    # Todo: Common build script or config?
