[project]
site_name = "Pyaket"
site_description = "📦 Easy Python to Fast Executables"
site_author = "Tremeschin"
site_url  = "https://pyaket.tremeschin.com/"
repo_url  = "https://github.com/BrokenSource/Pyaket/"
repo_name = "BrokenSource/Pyaket"
copyright = "&copy; CC BY-SA 4.0, <a href='https://github.com/Tremeschin/'>Tremeschin</a> 🇧🇷"
docs_dir  = "website"
nav = [
  {Origin = "https://tremeschin.com/"},
  {Home = [
    "index.md",
    "changelog.md",
    "license.md",
  ]},
  {Get = [
    "get/index.md",
    {Packages = [
      "get/python.md",
      "get/release.md",
      "get/source.md",
      "get/docker.md",
    ]},
    {Workflows = [
      "get/ci/github.md",
      "get/ci/gitlab.md",
    ]},
    {Tools = [
      "get/rust.md",
    ]},
  ]},
  {Docs = [
    "docs/index.md",
    {Configuration = [
      "docs/project/application.md",
      "docs/project/dependencies.md",
      "docs/project/directories.md",
      "docs/project/python.md",
      "docs/project/pytorch.md",
      "docs/project/entry.md",
    ]},
    {Rust = [
      "docs/rust/profiles.md",
      "docs/rust/crosscompiling.md",
    ]},
    {Extra = [
      "docs/pinning.md",
    ]},
  ]},
  {Help = [
    {General = [
      "help/general.md",
      "help/alternatives.md",
    ]},
    {Systems = [
      "help/windows.md",
      "help/linux.md",
      "help/macos.md",
    ]},
  ]},
]

[project.theme]
name = "zentheme"
favicon = "assets/images/logo.png"

[project.theme.icon]
logo = "octicons/package-16"
tag.default = "material/tag"

[project.extra.tags]
dummy = "key"

[[project.extra.social]]
icon = "fontawesome/brands/discord"
link = "https://discord.gg/KjqvcYwRHm"

[[project.extra.social]]
icon = "fontawesome/brands/patreon"
link = "https://www.patreon.com/Tremeschin"

[[project.extra.social]]
icon = "fontawesome/brands/github"
link = "https://github.com/Tremeschin"
